### ISSUE TITLE
Coral Restoration 

### ISSUE THREAD

**Issue by meganejlott** [epid8060fall2019/WilliamNorfolk-Introduction#1]
Hi Billy, 

Thanks so much for your introduction! What an exciting career you've had in the sciences. I was hoping to learn more from you about your work with the Coral Restoration Foundation. Did you all have success cultivating coral species? What were the biggest challenges in cultivation or transplantation? Did you all select for coral species resistant to abundant pathogens in the Keys? 

Thanks!
Megan

**Comment by williamnorfolk** [comment]
Hi Megan,

Thank you for your interest in my background! I have added another sub-section to my introduction giving a description of my work with the Coral Restoration Foundation which should answer all of your questions. Feel free to follow-up with any further questions as additional Github Issues.

Billy
